### ISSUE TITLE
Add VMware ESX/ESXi/VCenter support

### ISSUE THREAD

**Issue by syphernl** [saltstack/salt-cloud#503]
This tool currently aims for public clouds, but it would greatly benefit from private clouds as well. I've come across a pretty good Python module for VMware ESX/ESXi/VCenter called [PySphere](https://github.com/gpmidi/pysphere) which allows VM's to be listed/started/stopped/created. 

My preliminary tests with this particular module have had pretty good results, it worked pretty well. 

It also allows files to be created/edited/removed and processes/scripts to be executed, so this means Salt/Salt-master can be installed to here as well, although this does require access to the root credentials. 

I came across a [thread](https://groups.google.com/forum/#!topic/salt-users/Dvp_pV2vQXo) on the Google Groups regarding the integration of ESXi, but since I don't post there myself I'd still want to share this.

**Comment by nmadhok** [comment]
This issue can be closed I believe in favor of https://github.com/saltstack/salt/pull/22258

Getting Started: http://docs.saltstack.com/en/latest/topics/cloud/vmware.html
Docs: http://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.vmware.html

**Comment by rallytime** [comment]
Good call @nmadhok! Thanks!
